_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 149d7587-e5e5-4d1a-820c-b5440141a635
name: 'The Program in Applied & Computational Mathematics'
mail: pacmweb@pacm.princeton.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
